import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { Activity, AlertTriangle, Bell, CalendarClock, CheckCircle2, ClipboardList, Radio, ShieldCheck, Siren } from 'lucide-react'
import { getCurrentUser, getPreferredUserName } from '../../lib/auth'
import { listNotifications } from '../../lib/notificationsApi'
import { listResponderIncidents } from '../../lib/responderApi'
import { ResponderShell } from './ResponderComponents'
import { normalizeIncident } from './responderUtils'

const closed = new Set(['completed', 'resolved', 'cancelled', 'rejected'])
const activity = [['System check completed', 'All systems operational', '2h ago', CheckCircle2, 'bg-emerald-100 text-emerald-600'], ['New training module available', 'First Aid Refresher Course', '5h ago', ClipboardList, 'bg-violet-100 text-violet-600'], ['Equipment inventory updated', '3 items updated', '8h ago', ShieldCheck, 'bg-amber-100 text-amber-600'], ['Community alert sent', 'Heavy rainfall expected', '1d ago', Bell, 'bg-blue-100 text-blue-600']]
function Metric({ icon: Icon, value, label, detail, tone }) { return <article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex gap-4"><span className={`flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl ${tone}`}><Icon className="h-7 w-7" /></span><div><p className="text-3xl font-extrabold leading-7 text-slate-800">{value}</p><h2 className="mt-1 font-semibold text-slate-700">{label}</h2><p className="mt-2 text-sm leading-5 text-slate-500">{detail}</p></div></div></article> }

export default function ResponderDashboard() {
  const user = getCurrentUser() || {}; const [incidents, setIncidents] = useState([]); const [notifications, setNotifications] = useState([]); const [loading, setLoading] = useState(true); const [online, setOnline] = useState(true)
  useEffect(() => { let cancelled = false; const load = async () => { try { const [data, notices] = await Promise.all([listResponderIncidents(25), listNotifications(8).catch(() => ({ notifications: [] }))]); if (!cancelled) { setIncidents((data.reports || []).map(normalizeIncident)); setNotifications(notices.notifications || []) } } catch { if (!cancelled) setIncidents([]) } finally { if (!cancelled) setLoading(false) } }; load(); const timer = window.setInterval(load, 15000); return () => { cancelled = true; window.clearInterval(timer) } }, [])
  const active = incidents.filter((item) => !closed.has(String(item.status || '').toLowerCase())); const assigned = active.filter((item) => item.assignedResponderId === user.uid || item.assignmentStatus === 'Assigned' || item.status === 'Assigned'); const critical = active.filter((item) => ['Critical', 'High'].includes(item.severity)).length; const unread = notifications.filter((item) => !item.read).length; const name = getPreferredUserName(user) || 'Responder'
  const metrics = useMemo(() => [{ icon: Siren, value: active.length, label: 'Active Emergencies', detail: 'Live incidents requiring attention', tone: 'bg-red-50 text-red-500' }, { icon: CalendarClock, value: assigned.length, label: 'Assigned Today', detail: 'Incidents assigned to you', tone: 'bg-blue-50 text-blue-500' }, { icon: AlertTriangle, value: critical, label: 'Critical Load', detail: 'High severity items in queue', tone: 'bg-amber-50 text-amber-500' }, { icon: Bell, value: unread, label: 'Unread Notices', detail: 'Updates and alerts pending', tone: 'bg-emerald-50 text-emerald-500' }], [active.length, assigned.length, critical, unread])
  return <ResponderShell><section className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><h1 className="text-3xl font-extrabold tracking-tight text-slate-800">Good morning, {name} <span aria-hidden="true">👋</span></h1><p className="mt-2 text-lg text-slate-500">Here's what's happening in your area today.</p></div><div className="flex flex-wrap gap-3"><Link to="/responder/report-emergency" className="inline-flex items-center gap-2 rounded-xl bg-red-600 px-5 py-3 font-bold text-white shadow-lg shadow-red-200 hover:bg-red-700"><Siren className="h-5 w-5" />Report Emergency</Link><Link to="/responder/incidents" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-5 py-3 font-bold text-slate-700 hover:bg-slate-50"><ClipboardList className="h-5 w-5" />Open Incidents</Link><Link to="/responder/dispatch" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-5 py-3 font-bold text-slate-700 hover:bg-slate-50"><Radio className="h-5 w-5" />Dispatch Center</Link></div></section>
    <section className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{metrics.map((item) => <Metric key={item.label} {...item} />)}</section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.05fr_.9fr_.9fr]">
      <article className="min-h-[390px] rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="flex items-center gap-3 text-lg font-bold text-slate-800"><ClipboardList className="h-5 w-5 text-red-500" />Today's Assignments</h2><Link to="/responder/assigned" className="text-sm font-semibold text-red-500">View all</Link></div>{loading ? <p className="py-20 text-center text-sm text-slate-500">Loading assignments...</p> : assigned.length ? <div className="mt-5 grid gap-3">{assigned.slice(0, 3).map((item) => <Link key={item.id} to={`/responder/incidents/${encodeURIComponent(item.id)}`} className="rounded-xl border border-slate-200 p-4 hover:border-red-200"><strong className="block text-slate-800">{item.title}</strong><span className="mt-2 block text-sm text-slate-500">{item.location}</span></Link>)}</div> : <div className="flex min-h-[300px] flex-col items-center justify-center text-center"><span className="flex h-20 w-20 items-center justify-center rounded-full bg-slate-100 text-slate-400"><ClipboardList className="h-9 w-9" /></span><h3 className="mt-5 text-lg font-bold text-slate-600">No assignments yet</h3><p className="mt-2 max-w-xs text-sm leading-6 text-slate-500">You're all caught up! New assignments will appear here.</p></div>}</article>
      <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="flex items-center gap-3 text-lg font-bold text-slate-800"><Activity className="h-5 w-5 text-red-500" />Recent Activity</h2><Link to="/responder/notifications" className="text-sm font-semibold text-red-500">View all</Link></div><div className="mt-5 grid gap-5">{activity.map(([title, text, time, Icon, tone]) => <div key={title} className="flex gap-3"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-full ${tone}`}><Icon className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><strong className="text-sm text-slate-700">{title}</strong><time className="whitespace-nowrap text-xs text-slate-400">{time}</time></div><p className="mt-1 text-sm text-slate-500">{text}</p></div></div>)}</div><Link to="/responder/notifications" className="mt-6 flex justify-center rounded-xl border border-red-300 py-3 text-sm font-bold text-red-600 hover:bg-red-50">View full activity log</Link></article>
      <div className="grid gap-6 content-start"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-3 text-lg font-bold text-slate-800"><Activity className="h-5 w-5 text-red-500" />Quick Stats</h2><div className="mt-6 flex items-center gap-7"><div className="flex h-32 w-32 shrink-0 flex-col items-center justify-center rounded-full border-[18px] border-slate-200"><strong className="text-4xl text-slate-800">{active.length}</strong><span className="text-sm text-slate-500">Total</span></div><ul className="grid gap-3 text-sm text-slate-500"><li><i className="mr-2 inline-block h-3 w-3 rounded-full bg-red-500" />{active.length} Active</li><li><i className="mr-2 inline-block h-3 w-3 rounded-full bg-blue-500" />{assigned.length} Assigned</li><li><i className="mr-2 inline-block h-3 w-3 rounded-full bg-emerald-500" />0 Resolved</li><li><i className="mr-2 inline-block h-3 w-3 rounded-full bg-slate-300" />0 Cancelled</li></ul></div></article><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="flex items-center gap-3 text-lg font-bold text-slate-800"><ShieldCheck className="h-5 w-5 text-red-500" />System Status</h2><Link to="/responder/resources" className="text-sm font-semibold text-red-500">View all</Link></div><div className="mt-4 flex items-center gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><CheckCircle2 className="h-7 w-7 text-emerald-600" /><div><strong className="text-sm text-emerald-800">All Systems Operational</strong><p className="mt-1 text-xs text-emerald-700">Last checked: Just now</p></div></div></article><button type="button" onClick={() => setOnline((value) => !value)} className={`rounded-2xl border p-4 text-left shadow-sm ${online ? 'border-emerald-200 bg-emerald-50' : 'border-slate-200 bg-white'}`}><strong className={online ? 'text-emerald-800' : 'text-slate-700'}>{online ? 'You are online and ready' : 'You are currently offline'}</strong><span className="mt-1 block text-sm text-slate-500">Click to change availability.</span></button></div>
    </section><footer className="pt-9 text-center text-sm text-slate-500">© 2026 Jirani Alert Emergency Responder Portal. All rights reserved.</footer></ResponderShell>
}
